package ru.urfu.SecondLabTask.exception;


public record ErrorResponse(String errorCode, String errorMessage) {
}
